// scripts/data.ts

export const departmentsData = [
  { name: "Sciences", officeLocation: "Block A - Room 12", contactEmail: "sciences@school.edu" },
  { name: "Languages", officeLocation: "Block B - Room 4", contactEmail: "languages@school.edu" },
  { name: "Humanities", officeLocation: "Block B - Room 9", contactEmail: "humanities@school.edu" },
  { name: "Mathematics & Computing", officeLocation: "Block C - Room 2", contactEmail: "mathcomputing@school.edu" },
  { name: "Physical Education", officeLocation: "Sports Complex - Room 1", contactEmail: "pe@school.edu" },
  { name: "Arts & Design", officeLocation: "Arts Block - Room 3", contactEmail: "arts@school.edu" },
  { name: "Business Studies", officeLocation: "Block D - Room 5", contactEmail: "business@school.edu" },
  { name: "Religious Studies", officeLocation: "Block B - Room 11", contactEmail: "religious@school.edu" },
  { name: "Technical & Vocational", officeLocation: "Workshop Block - Room 2", contactEmail: "technical@school.edu" },
  { name: "Special Education", officeLocation: "Resource Center - Room 1", contactEmail: "specialed@school.edu" },
  { name: "Guidance & Counseling", officeLocation: "Admin Block - Room 8", contactEmail: "counseling@school.edu" },
  { name: "Library & Information", officeLocation: "Library Block - Main", contactEmail: "library@school.edu" },
  { name: "Agriculture", officeLocation: "Farm Block - Room 1", contactEmail: "agriculture@school.edu" },
  { name: "Music", officeLocation: "Arts Block - Room 7", contactEmail: "music@school.edu" },
  { name: "Drama & Theatre", officeLocation: "Arts Block - Room 9", contactEmail: "drama@school.edu" },
  { name: "Home Economics", officeLocation: "Home Ec Block - Room 2", contactEmail: "homeec@school.edu" },
  { name: "Information Technology", officeLocation: "ICT Center - Room 1", contactEmail: "ict@school.edu" },
  { name: "Modern Languages", officeLocation: "Block B - Room 6", contactEmail: "modernlang@school.edu" },
  { name: "Classical Studies", officeLocation: "Block B - Room 14", contactEmail: "classical@school.edu" },
  { name: "Environmental Studies", officeLocation: "Science Block - Room 18", contactEmail: "environmental@school.edu" },
]

export const teacherNames: [string, string][] = [
  ["Linda", "Martinez"],
  ["Robert", "Taylor"],
  ["James", "Ncube"],
  ["Grace", "Moyo"],
  ["Peter", "Chikafu"],
  ["Sarah", "Johnson"],
  ["Michael", "Chen"],
  ["Emily", "Williams"],
  ["David", "Rodriguez"],
  ["Tanaka", "Chuma"],
  ["Rutendo", "Gwenzi"],
  ["Farai", "Mudzingwa"],
  ["Chipo", "Nyathi"],
  ["Blessing", "Sibanda"],
  ["Tapiwa", "Marufu"],
  ["Anesu", "Chirwa"],
  ["Vimbai", "Dube"],
  ["Kudzai", "Moyana"],
  ["Tafara", "Gumbo"],
  ["Nyasha", "Chirara"],
]

export const studentNames: [string, string][] = [
  ["Emily", "Johnson"],
  ["Michael", "Chen"],
  ["Sarah", "Williams"],
  ["James", "Rodriguez"],
  ["Tanaka", "Chuma"],
  ["Rutendo", "Gwenzi"],
  ["Farai", "Mudzingwa"],
  ["Chipo", "Nyathi"],
  ["Blessing", "Sibanda"],
  ["Tapiwa", "Marufu"],
  ["Anesu", "Chirwa"],
  ["Vimbai", "Dube"],
  ["Kudzai", "Moyana"],
  ["Tafara", "Gumbo"],
  ["Nyasha", "Chirara"],
  ["Tinashe", "Mupunga"],
  ["Ropafadzo", "Chikwava"],
  ["Tatenda", "Mhaka"],
  ["Munashe", "Gwaunza"],
  ["Nokutenda", "Mupfumi"],
]

export const subjectsList = [
  "Mathematics",
  "English Language",
  "Biology",
  "Chemistry",
  "Physics",
  "History",
  "Geography",
  "Computer Science",
  "Literature",
  "French",
  "Shona",
  "Ndebele",
  "Agriculture",
  "Commerce",
  "Accounting",
  "Economics",
  "Business Studies",
  "Art & Design",
  "Music",
  "Physical Education",
]

export const qualifications = [
  "BSc Education",
  "MEd",
  "BA Honours",
  "PGDE",
  "BSc Mathematics",
  "BSc Physics",
  "BA English",
  "MSc Chemistry",
  "BEd",
  "MBA",
  "PhD Education",
  "MA History",
  "BSc Computer Science",
  "BCom",
  "BSc Agriculture",
  "BA Fine Arts",
  "BSc Environmental Science",
  "BA Humanities",
  "MEd Counseling",
  "BSc Sports Science",
]

export const levelsForms = [
  { level: "O-Level", form: "Form 1" },
  { level: "O-Level", form: "Form 2" },
  { level: "O-Level", form: "Form 3" },
  { level: "O-Level", form: "Form 4" },
  { level: "A-Level", form: "Lower Six" },
  { level: "A-Level", form: "Upper Six" },
  { level: "O-Level", form: "Form 1A" },
  { level: "O-Level", form: "Form 1B" },
  { level: "O-Level", form: "Form 2A" },
  { level: "O-Level", form: "Form 2B" },
  { level: "O-Level", form: "Form 3A" },
  { level: "O-Level", form: "Form 3B" },
  { level: "O-Level", form: "Form 4A" },
  { level: "O-Level", form: "Form 4B" },
  { level: "A-Level", form: "Lower Six A" },
  { level: "A-Level", form: "Lower Six B" },
  { level: "A-Level", form: "Upper Six A" },
  { level: "A-Level", form: "Upper Six B" },
  { level: "Primary", form: "Grade 7" },
  { level: "Primary", form: "Grade 6" },
]

export const examDefs = [
  { name: "Mid-Term Test", term: "Term 1", monthOffset: 2 },
  { name: "End of Term Exam", term: "Term 1", monthOffset: 3 },
  { name: "Mock Exam", term: "Term 2", monthOffset: 6 },
  { name: "Final Exam", term: "Term 2", monthOffset: 7 },
  { name: "Internal Assessment", term: "Term 1", monthOffset: 1 },
  { name: "Practice Test", term: "Term 2", monthOffset: 5 },
  { name: "CAT Test", term: "Term 1", monthOffset: 1.5 },
  { name: "Project Evaluation", term: "Term 2", monthOffset: 5.5 },
  { name: "Oral Assessment", term: "Term 1", monthOffset: 2.5 },
  { name: "Practical Exam", term: "Term 2", monthOffset: 6.5 },
  { name: "Written Test", term: "Term 1", monthOffset: 0.5 },
  { name: "Comprehensive Exam", term: "Term 2", monthOffset: 7.5 },
  { name: "Quiz Series", term: "Term 1", monthOffset: 1.5 },
  { name: "Semester Exam", term: "Term 2", monthOffset: 6 },
  { name: "Diagnostic Test", term: "Term 1", monthOffset: 2.5 },
  { name: "Progress Test", term: "Term 2", monthOffset: 5.5 },
  { name: "Terminal Exam", term: "Term 1", monthOffset: 3.5 },
  { name: "Board Mock", term: "Term 2", monthOffset: 7 },
  { name: "Class Test", term: "Term 1", monthOffset: 0.5 },
  { name: "Final Assessment", term: "Term 2", monthOffset: 8 },
]

export const disciplineDefs = [
  { incident: "Late to class", actionTaken: "Verbal warning", remarks: "First offense" },
  { incident: "Uniform violation", actionTaken: "Written warning", remarks: "Repeat noted" },
  { incident: "Unauthorized phone use", actionTaken: "Phone confiscated", remarks: "Returned end of day" },
  { incident: "Disruptive behavior", actionTaken: "Parent meeting scheduled", remarks: "Follow-up required" },
  { incident: "Bullying", actionTaken: "Suspension", remarks: "1 day suspension" },
  { incident: "Cheating on exam", actionTaken: "Zero marks awarded", remarks: "Parent notified" },
  { incident: "Littering", actionTaken: "Cleanup duty", remarks: "Community service" },
  { incident: "Fighting", actionTaken: "Suspension", remarks: "3 days suspension" },
  { incident: "Insubordination", actionTaken: "Detention", remarks: "2 hours detention" },
  { incident: "Forgery", actionTaken: "Disciplinary hearing", remarks: "Referral to head" },
  { incident: "Theft", actionTaken: "Suspension", remarks: "Recovery of item" },
  { incident: "Truancy", actionTaken: "Parent conference", remarks: "Absent without leave" },
  { incident: "Verbal abuse", actionTaken: "Community service", remarks: "Apology required" },
  { incident: "Damage to property", actionTaken: "Compensation ordered", remarks: "School property" },
  { incident: "Smoking", actionTaken: "Suspension", remarks: "Health violation" },
  { incident: "Use of foul language", actionTaken: "Written warning", remarks: "Second offense" },
  { incident: "Failure to complete homework", actionTaken: "Detention", remarks: "Pattern observed" },
  { incident: "Disturbing class", actionTaken: "Seat moved", remarks: "Temporary measure" },
  { incident: "Hate speech", actionTaken: "Disciplinary hearing", remarks: "Serious offense" },
  { incident: "Bribery", actionTaken: "Suspension pending investigation", remarks: "Student involved" },
]

export const roles = [
  "admin",
  "teacher",
  "student",
  "applicant",
]

export const feeCategories = [
  "Tuition Fee",
  "Sports Fee",
  "Lab Fee",
  "Library Fee",
  "Technology Fee",
  "Boarding Fee",
  "Transport Fee",
  "Uniform Fee",
  "Activity Fee",
  "Exam Fee",
  "PTA Levy",
  "Building Levy",
  "Insurance Fee",
  "Book Fee",
  "Stationery Fee",
]

export const paymentMethods = [
  "cash",
  "bank_transfer",
  "mobile_money",
  "card",
  "cheque",
]

export const statusOptions = [
  "pending",
  "completed",
  "failed",
  "refunded",
  "cancelled",
]

// Hostel names
export const hostelNames = [
  "Milton Hostel",
  "Livingstone Hostel",
  "Victoria Hostel",
  "Zambezi Hostel",
  "Kariba Hostel",
  "Nyanga Hostel",
  "Chimanimani Hostel",
  "Mana Pools Hostel",
]

// Transport routes
export const transportRoutes = [
  { description: "Route 1 - City Center to School", startPoint: "City Center", endPoint: "School" },
  { description: "Route 2 - Suburb A to School", startPoint: "Suburb A", endPoint: "School" },
  { description: "Route 3 - Suburb B to School", startPoint: "Suburb B", endPoint: "School" },
  { description: "Route 4 - Township to School", startPoint: "Township", endPoint: "School" },
  { description: "Route 5 - Rural Area to School", startPoint: "Rural Area", endPoint: "School" },
  { description: "Route 6 - Farm to School", startPoint: "Farm Area", endPoint: "School" },
]