// config/appwrite.ts
import { Client, Databases, Storage, Account } from 'appwrite';

export const appwriteConfig = {
  endpoint: process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT!,
  projectId: process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID!,
  databaseId: process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!,
  schoolBucketId: process.env.NEXT_PUBLIC_APPWRITE_SCHOOL_BUCKET_ID!,
};

// Initialize Appwrite client
export const client = new Client()
  .setEndpoint(appwriteConfig.endpoint)
  .setProject(appwriteConfig.projectId);

export const databases = new Databases(client);
export const storage = new Storage(client);
export const account = new Account(client);

// Collection IDs for easy reference
export const COLLECTIONS = {
  SCHOOLS: process.env.NEXT_PUBLIC_APPWRITE_SCHOOLS_COLLECTION_ID!,
  USERS: process.env.NEXT_PUBLIC_APPWRITE_USERS_COLLECTION_ID!,
  ADMINS: process.env.NEXT_PUBLIC_APPWRITE_ADMINS_COLLECTION_ID!,
  APPLICANTS: process.env.NEXT_PUBLIC_APPWRITE_APPLICANTS_COLLECTION_ID!,
  STUDENTS: process.env.NEXT_PUBLIC_APPWRITE_STUDENTS_COLLECTION_ID!,
  TEACHERS: process.env.NEXT_PUBLIC_APPWRITE_TEACHERS_COLLECTION_ID!,
  DEPARTMENTS: process.env.NEXT_PUBLIC_APPWRITE_DEPARTMENTS_COLLECTION_ID!,
  SUBJECTS: process.env.NEXT_PUBLIC_APPWRITE_SUBJECTS_COLLECTION_ID!,
  CLASSES: process.env.NEXT_PUBLIC_APPWRITE_CLASSES_COLLECTION_ID!,
  TEACHER_SUBJECTS: process.env.NEXT_PUBLIC_APPWRITE_TEACHER_SUBJECTS_COLLECTION_ID!,
  STUDENT_SUBJECTS: process.env.NEXT_PUBLIC_APPWRITE_STUDENT_SUBJECTS_COLLECTION_ID!,
  ATTENDANCE: process.env.NEXT_PUBLIC_APPWRITE_ATTENDANCE_COLLECTION_ID!,
  TIMETABLE: process.env.NEXT_PUBLIC_APPWRITE_TIMETABLE_COLLECTION_ID!,
  EXAMS: process.env.NEXT_PUBLIC_APPWRITE_EXAMS_COLLECTION_ID!,
  MARKS: process.env.NEXT_PUBLIC_APPWRITE_MARKS_COLLECTION_ID!,
  FEES: process.env.NEXT_PUBLIC_APPWRITE_FEES_COLLECTION_ID!,
  PAYMENTS: process.env.NEXT_PUBLIC_APPWRITE_PAYMENTS_COLLECTION_ID!,
  DISCIPLINE: process.env.NEXT_PUBLIC_APPWRITE_DISCIPLINE_COLLECTION_ID!,
  HOSTEL_STUDENTS: process.env.NEXT_PUBLIC_APPWRITE_HOSTEL_STUDENTS_COLLECTION_ID!,
  HOSTELS: process.env.NEXT_PUBLIC_APPWRITE_HOSTELS_COLLECTION_ID!,
  STUDENT_TRANSPORT: process.env.NEXT_PUBLIC_APPWRITE_STUDENT_TRANSPORT_COLLECTION_ID!,
  TRANSPORT_ROUTES: process.env.NEXT_PUBLIC_APPWRITE_TRANSPORT_ROUTES_COLLECTION_ID!,
  ANNOUNCEMENTS: process.env.NEXT_PUBLIC_APPWRITE_ANNOUNCEMENTS_COLLECTION_ID!,
  CALENDAR: process.env.NEXT_PUBLIC_APPWRITE_CALENDAR_COLLECTION_ID!,
  INVENTORY: process.env.NEXT_PUBLIC_APPWRITE_INVENTORY_COLLECTION_ID!,
} as const;

// Bucket IDs
export const BUCKETS = {
  SCHOOL: process.env.NEXT_PUBLIC_APPWRITE_SCHOOL_BUCKET_ID!,
} as const;